### ISSUE TITLE
raises json parser error when server returns http error

### ISSUE THREAD

**Issue by molobrakos** [6D66/eliq#6]
Not sure how you would like to handle this - maybe it is up to the caller to take care of this situation.
The ELIQ Online servers seem to return 404 Bad request sometimes (at least for me).

HTTP Error 400: Bad Request
'"user have no current power data"'

This makes the self._tools.get_data_from_eliq function return None (https://github.com/6D66/eliq/blob/master/eliqonline/tools.py#L65)

And then the json parsing of None will throw exception (TypeError: the JSON object must be str, not 'NoneType') at https://github.com/6D66/eliq/blob/master/eliqonline/api.py#L112 since it tries to parse None as json.

Suggestion: either let the HTTP error fall through to the caller since it makes more sense to catch a HTTP error than a JSON parser error/Type error. Or just return None or an empty DataNow object to the caller.

**Comment by 6D66** [comment]
It sounds like a clever solution, I will add you to the repo so you can push it directly. :)

**Comment by 6D66** [comment]
Sorry, i think its better to trow a http error..  :)
I will remove try/except for HTTP error in tools.py.

**Comment by molobrakos** [comment]
This fix also makes it possible for the caller to handle the new API limit: https://my.eliq.se/knowledge/sv-SE/56-api/701-limits-p%C3%A5-api

Are you planning on releasing a new version with this fix included?

**Comment by 6D66** [comment]
I had a "better coverage" on my todo-list before a new release, but I will do a new release now without that. I can fix that in a later release.

**Comment by 6D66** [comment]
Ops, forgot that i did a release with this fix, https://github.com/6D66/eliq/releases/tag/1.0.11
